import { MenuItem } from '@/types';

export const menuItems: MenuItem[] = [
  // ─── HOT ────────────────────────────────────────────────────────────────
  {
    id: 'americano-pino',
    name: 'Americano del Pino',
    description:
      'Un café negro de extracción clásica, limpio y profundamente equilibrado. Notas de nuez tostada, cacao ligero y un final suave que se alarga como el eco entre los pinos. Sin adornos, sin distracciones — solo café en su forma más honesta. Ideal para quienes aprecian la pureza del grano y necesitan un inicio de mañana que hable por sí solo.',
    price: 45,
    category: 'hot',
    emoji: '☕',
    brewType: 'Classic',
    brewSize: 'Cup 8 oz',
    tags: ['negro', 'clásico', 'suave'],
    prepSteps: [
      'Llenar el depósito de agua hasta la marca de 8 oz.',
      'Colocar el filtro permanente en la canastilla y agregar 2 cucharadas colmadas de café molido.',
      'Presionar el botón de tamaño hasta seleccionar Cup → 8 oz.',
      'Presionar BREW TYPE hasta ver "Classic" en la pantalla.',
      'Presionar BREW y esperar la extracción completa (~3 min).',
      'Servir directamente en la taza. Disfrutar solo o con un toque de azúcar morena.',
    ],
  },
  {
    id: 'latte-cabana',
    name: 'Latte de Cabaña',
    description:
      'Un concentrado intenso de café cubierto con leche suavemente calentada, sedosa y envolvente. Cada sorbo es como sentarse frente a una chimenea encendida después de un largo paseo por el bosque — reconfortante, cremoso y profundamente cálido. El balance entre la intensidad del café y la dulzura natural de la leche crea una armonía que abraza desde adentro.',
    price: 65,
    category: 'hot',
    emoji: '🥛',
    brewType: 'Specialty',
    brewSize: 'Cup 6 oz',
    tags: ['con leche', 'cremoso', 'specialty'],
    prepSteps: [
      'Llenar el depósito de agua hasta la marca de 6 oz.',
      'Colocar el filtro y agregar 2 cucharadas muy colmadas de café molido (más cantidad = más concentrado).',
      'Presionar el botón de tamaño hasta seleccionar Cup → 6 oz.',
      'Presionar BREW TYPE hasta ver "Specialty" — esto produce un concentrado tipo espresso.',
      'Presionar BREW y esperar la extracción (~2 min).',
      'Mientras tanto, calentar 180 ml de leche entera en microondas 45 seg, o espumar con espumador de leche.',
      'Verter el concentrado en la taza, añadir la leche caliente lentamente.',
      'Opcional: espolvorear canela o cacao en polvo al gusto.',
    ],
  },
  {
    id: 'cappuccino-sierra',
    name: 'Cappuccino Sierra Nevada',
    description:
      'La elegancia italiana trasladada a la altura de la sierra. Un concentrado de café intenso coronado por una microespuma densa, aterciopelada y brillante que recuerda a la nieve fresca sobre las cumbres. El contraste entre la fuerza del café y la ligereza de la espuma lo convierte en una experiencia de texturas tan placentera como contemplar las montañas al amanecer.',
    price: 70,
    category: 'hot',
    emoji: '🫧',
    brewType: 'Specialty',
    brewSize: 'Cup 6 oz',
    tags: ['espuma', 'specialty', 'italiano'],
    prepSteps: [
      'Llenar el depósito de agua hasta la marca de 6 oz.',
      'Agregar 2 cucharadas muy colmadas de café al filtro permanente.',
      'Seleccionar Cup → 6 oz y presionar BREW TYPE → "Specialty".',
      'Presionar BREW para extraer el concentrado.',
      'Espumar 90 ml de leche fría con espumador hasta obtener microespuma densa y brillante.',
      'Verter el concentrado en la taza.',
      'Añadir la leche espumada con movimiento circular suave.',
      'Coronar con la espuma y espolvorear cacao en polvo o canela.',
    ],
  },
  {
    id: 'taza-rica-montana',
    name: 'Taza Rica de Montaña',
    description:
      'El modo Rich extrae el café a paso lento y deliberado, exprimiendo cada matiz del grano hasta el último. El resultado es una taza de cuerpo robusto con notas a tierra húmeda, madera oscura y un amargor noble que despierta los sentidos sin agredir. Para las mañanas en que el frío de la sierra pide algo que caliente no solo el cuerpo, sino también el espíritu.',
    price: 50,
    category: 'hot',
    emoji: '🏔️',
    brewType: 'Rich',
    brewSize: 'Cup 6 oz',
    tags: ['intenso', 'fuerte', 'negro'],
    prepSteps: [
      'Llenar el depósito de agua hasta la marca de 6 oz.',
      'Agregar 2½ cucharadas de café al filtro — el modo Rich extrae a ritmo más lento.',
      'Seleccionar Cup → 6 oz.',
      'Presionar BREW TYPE hasta ver "Rich" en pantalla.',
      'Presionar BREW — la extracción es más lenta para mayor cuerpo e intensidad.',
      'Servir solo. Ideal con azúcar morena o una pizca de sal para realzar el sabor.',
    ],
  },
  {
    id: 'miel-abeto',
    name: 'Café Miel de Abeto',
    description:
      'Una receta nacida en las laderas del bosque. Café de extracción profunda que se funde con miel de flores silvestres, canela molida y una pizca de vainilla para crear algo verdaderamente especial. La dulzura no es artificiosa — es la misma que ofrece la naturaleza: compleja, aromática y cálida. Como caminar entre abetos al amanecer mientras el mundo todavía duerme.',
    price: 60,
    category: 'hot',
    emoji: '🍯',
    brewType: 'Rich',
    brewSize: 'Cup 8 oz',
    tags: ['dulce', 'miel', 'canela', 'aromatizado'],
    prepSteps: [
      'Llenar el depósito de agua hasta la marca de 8 oz.',
      'Agregar 2 cucharadas de café al filtro permanente.',
      'Seleccionar Cup → 8 oz y BREW TYPE → "Rich". Presionar BREW.',
      'En la taza destino, combinar: 1 cucharadita de miel, ¼ cucharadita de canela molida, 2-3 gotas de extracto de vainilla.',
      'Verter el café caliente sobre la mezcla mientras aún está extrayendo.',
      'Revolver bien con cuchara de madera hasta integrar completamente.',
      'Opcional: añadir un stick de canela y unas gotas de leche.',
    ],
  },
  {
    id: 'mocha-cumbre',
    name: 'Mocha de la Cumbre',
    description:
      'Donde el café y el chocolate oscuro encuentran su destino común. Un concentrado potente se mezcla con pasta de cacao sin azúcar, creando una base intensa que la leche suaviza en una bebida de profundidad extraordinaria. Notas a chocolate amargo, café tostado y un final largo y aterciopelado. Para los momentos en que solo algo sublime alcanza la altura de las expectativas.',
    price: 75,
    category: 'hot',
    emoji: '🍫',
    brewType: 'Specialty',
    brewSize: 'Cup 6 oz',
    tags: ['chocolate', 'dulce', 'cremoso', 'specialty'],
    prepSteps: [
      'Llenar el depósito de agua hasta la marca de 6 oz.',
      'Agregar 2 cucharadas colmadas de café al filtro.',
      'Seleccionar Cup → 6 oz y BREW TYPE → "Specialty". Presionar BREW.',
      'En la taza, mezclar: 1 cucharada de cacao en polvo sin azúcar + 1 cucharadita de azúcar + 1 cucharada de agua caliente. Revolver hasta formar una pasta homogénea.',
      'Verter el concentrado caliente sobre la pasta de chocolate y mezclar.',
      'Añadir 100 ml de leche entera caliente o espumada.',
      'Decorar con cacao en polvo, chispas de chocolate oscuro o una pizca de flor de sal.',
    ],
  },

  // ─── COLD ────────────────────────────────────────────────────────────────
  {
    id: 'cold-brew-bosque',
    name: 'Cold Brew del Bosque',
    description:
      'Café extraído directamente sobre hielo para capturar lo mejor del grano: más suave, menos ácido y con una dulzura natural sorprendente. Notas herbales, terrosas y un fondo que evoca el olor del musgo mojado y la tierra fresca del bosque tras la lluvia. Sin amargor forzado, sin complicaciones — solo café en su forma más refrescante y honesta. Un clásico que no necesita pretextos.',
    price: 65,
    category: 'cold',
    emoji: '🌲',
    brewType: 'Over Ice',
    brewSize: 'Cup 8 oz',
    tags: ['frío', 'suave', 'refrescante'],
    prepSteps: [
      'Llenar el depósito de agua hasta la marca de Over Ice (8 oz).',
      'Agregar 2 cucharadas colmadas de café al filtro — la extracción Over Ice usa más café.',
      '⚠️ IMPORTANTE: Llenar el vaso completamente con hielo antes de colocarlo bajo la boquilla.',
      'Seleccionar Cup → 8 oz.',
      'Presionar BREW TYPE hasta ver "Over Ice" — el café se extrae más concentrado y rápido.',
      'Presionar BREW — el café caliente cae directamente sobre el hielo y se enfría de golpe.',
      'Agregar leche, crema o jarabe de sabor al gusto. Servir inmediatamente.',
    ],
  },
  {
    id: 'iced-latte-sierra',
    name: 'Iced Latte Sierra',
    description:
      'Un concentrado intenso que cae lentamente sobre un vaso lleno de hielo y se funde con leche fría en un gradiente de colores cálidos. La primera probada es un golpe refrescante; lo que sigue es la suavidad cremosa del café con leche a temperatura perfecta. Ideal para los días en que el sol calienta las cumbres y el cuerpo pide algo que refresque el alma sin sacrificar sabor.',
    price: 70,
    category: 'cold',
    emoji: '🧊',
    brewType: 'Specialty',
    brewSize: 'Cup 6 oz',
    tags: ['frío', 'con leche', 'cremoso'],
    prepSteps: [
      'Llenar el depósito de agua hasta la marca de 6 oz.',
      'Agregar 2 cucharadas muy colmadas de café al filtro.',
      'Seleccionar Cup → 6 oz y BREW TYPE → "Specialty". Presionar BREW.',
      'Dejar enfriar el concentrado 2-3 minutos a temperatura ambiente.',
      'En un vaso alto, colocar hielo hasta el tope.',
      'Verter el concentrado sobre el hielo lentamente.',
      'Añadir 150 ml de leche entera fría o bebida de avena. Revolver con pajilla y servir.',
    ],
  },
  {
    id: 'frappe-lena',
    name: 'Frappé de Leña',
    description:
      'Concentrado mezclado con hielo, leche y vainilla ahumada. Fogón de montaña convertido en bebida.',
    price: 80,
    category: 'cold',
    emoji: '🔥',
    brewType: 'Specialty',
    brewSize: 'Cup 6 oz',
    tags: ['frío', 'blended', 'cremoso', 'dulce'],
    prepSteps: [
      'Preparar un concentrado Specialty de 6 oz (ver pasos del Latte de Cabaña).',
      'Dejar enfriar el concentrado en el congelador 5-8 minutos.',
      'En licuadora, combinar: 1 taza de hielo, el concentrado, 150 ml de leche entera, 1 cucharadita de extracto de vainilla ahumada, 1 cucharada de azúcar morena.',
      'Licuar a máxima velocidad 40 segundos hasta obtener textura suave y cremosa.',
      'Verter en vaso alto.',
      'Decorar con crema batida, espolvorear canela y añadir jarabe de caramelo si se desea.',
    ],
  },
  {
    id: 'cold-honey-haze',
    name: 'Cold Honey Haze',
    description:
      'Over Ice con miel silvestre y leche de avena. Suavidad amaderada con la dulzura del campo al atardecer.',
    price: 68,
    category: 'cold',
    emoji: '🌸',
    brewType: 'Over Ice',
    brewSize: 'Travel Mug 16 oz',
    tags: ['frío', 'miel', 'suave', 'vegano'],
    prepSteps: [
      'Llenar el depósito de agua hasta la marca de Over Ice para Travel Mug.',
      'Agregar 3 cucharadas de café al filtro permanente.',
      '⚠️ Llenar el Travel Mug o vaso completamente con hielo.',
      'Seleccionar Travel Mug → 16 oz.',
      'Presionar BREW TYPE → "Over Ice". Presionar BREW.',
      'Una vez extraído, añadir 1½ cucharaditas de miel líquida directamente.',
      'Revolver enérgicamente hasta disolver. Añadir 100 ml de leche de avena fría.',
      'Ajustar dulzor con más miel si se desea. Servir con tapa y pajilla.',
    ],
  },
];
