import { MenuItem } from '@/types';

export const menuItems: MenuItem[] = [
  // ─── HOT ────────────────────────────────────────────────────────────────
  {
    id: 'cappuccino-vainilla',
    name: 'Cappuccino de Vainilla',
    description:
      'Un doble shot de espresso envuelto en una nube de leche entera perfectamente espumada, tocado con la dulzura de la vainilla que transforma cada sorbo en algo más que café. La espuma densa y aterciopelada abraza el espresso como la niebla abraza los pinos al amanecer — suave, aromática y completamente irresistible. Para quienes buscan el equilibrio perfecto entre intensidad y dulzura en cada taza.',
    price: 70,
    category: 'hot',
    emoji: '☕',
    brewType: 'Espresso',
    brewSize: 'Doble shot (6½ oz)',
    tags: ['espresso', 'vainilla', 'espuma', 'cremoso'],
    ingredients: [
      'Doble shot de espresso',
      '1 cucharada de jarabe de vainilla',
      '5 oz (150 ml) de leche entera, fría',
    ],
    prepSteps: [
      'Insertar la canastilla doble en el portafiltro alineando las pestañas con las muescas. Colocar el embudo e insertar en la cuna de molido.',
      'Girar el dial central hasta iluminar ESPRESSO. Ajustar el dial de molido al tamaño recomendado y presionar START GRIND.',
      'Tampar los granos: presionar el tamper hasta que toque el embudo. Retirar el embudo y fijar el portafiltro en el grupo de extracción alineando los puntos naranjas.',
      'Agregar 1 cucharada de jarabe de vainilla en una taza de 8 oz. Colocar bajo el portafiltro y presionar START BREW.',
      'Agregar 5 oz de leche entera fría en la jarra. Colocar en la plataforma con la varita de vapor adentro.',
      'Presionar MILK TYPE hasta iluminar DAIRY. Girar el dial de espuma hasta THICK FROTH. Presionar START FROTH.',
      'Verter la leche espumada sobre el espresso y servir.',
    ],
  },
  {
    id: 'macchiato-caramelo',
    name: 'Macchiato de Caramelo',
    description:
      'Espresso intenso marcado con una corona de leche espumada y un hilo dorado de caramelo que desciende como la resina de pino bajo el sol de la tarde. Pequeño en tamaño, enorme en sabor — cada sorbo concentra la esencia del grano junto con la dulzura del caramelo en una experiencia que tarda más en recordarse que en beberse. El clásico de los clásicos, elevado a la altura de la sierra.',
    price: 60,
    category: 'hot',
    emoji: '🍮',
    brewType: 'Espresso',
    brewSize: 'Doble shot (3½ oz)',
    tags: ['espresso', 'caramelo', 'espuma', 'clásico'],
    ingredients: [
      'Doble shot de espresso',
      '1½ cucharaditas de jarabe de caramelo (+ extra para decorar)',
      '2 oz (60 ml) de leche entera',
    ],
    prepSteps: [
      'Insertar la canastilla doble en el portafiltro alineando las pestañas con las muescas. Colocar el embudo e insertar en la cuna de molido.',
      'Girar el dial central hasta iluminar ESPRESSO. Ajustar el dial de molido al tamaño recomendado y presionar START GRIND.',
      'Tampar los granos: presionar el tamper hasta que toque el embudo. Retirar el embudo y fijar el portafiltro en el grupo de extracción alineando los puntos naranjas.',
      'Agregar 1½ cucharaditas de jarabe de caramelo en una taza de 6 oz. Colocar bajo el portafiltro y presionar START BREW.',
      'Agregar 2 oz de leche entera en la jarra. Colocar en la plataforma con la varita de vapor adentro.',
      'Presionar MILK TYPE hasta iluminar DAIRY. Girar el dial hasta THICK FROTH. Presionar START FROTH.',
      'Verter la leche espumada sobre el espresso. Agregar un hilo extra de jarabe de caramelo encima y servir.',
    ],
  },
  {
    id: 'latte-canela-miel',
    name: 'Latte de Canela y Miel',
    description:
      'La calidez de la miel silvestre y el aroma de la canela molida se funden con un doble shot de espresso y una nube generosa de leche ligeramente espumada. Dulce sin ser empalagoso, especiado sin ser dominante — como el aroma del bosque después de la lluvia de otoño. Una receta que invita a quedarse, a sostener la taza con las dos manos y dejar que el tiempo pase más despacio.',
    price: 75,
    category: 'hot',
    emoji: '🍯',
    brewType: 'Espresso',
    brewSize: 'Doble shot (9½ oz)',
    tags: ['espresso', 'canela', 'miel', 'dulce', 'especiado'],
    ingredients: [
      'Doble shot de espresso',
      '8 oz (240 ml) de leche entera',
      '½ cucharadita de canela molida (+ extra para decorar)',
      '2 cucharaditas de miel',
    ],
    prepSteps: [
      'Insertar la canastilla doble en el portafiltro alineando las pestañas con las muescas. Colocar el embudo e insertar en la cuna de molido.',
      'Girar el dial central hasta iluminar ESPRESSO. Ajustar el dial de molido al tamaño recomendado y presionar START GRIND.',
      'Agregar ½ cucharadita de canela molida sobre el portafiltro y agitar suavemente para distribuir sobre los granos.',
      'Tampar los granos: presionar el tamper hasta que toque el embudo. Retirar el embudo y fijar el portafiltro en el grupo de extracción alineando los puntos naranjas.',
      'Agregar 2 cucharaditas de miel en una taza de 12 oz. Colocar bajo el portafiltro y presionar START BREW.',
      'Una vez extraído el espresso, mezclar la miel en el café caliente hasta disolver por completo.',
      'Agregar 8 oz de leche entera fría en la jarra. Colocar en la plataforma con la varita de vapor.',
      'Presionar MILK TYPE hasta iluminar DAIRY. Girar el dial hasta THIN FROTH. Presionar START FROTH.',
      'Verter la leche espumada sobre el espresso. Espolvorear canela al gusto y servir.',
    ],
  },
  {
    id: 'flat-white',
    name: 'Flat White',
    description:
      'La pureza del espresso encontrando su complemento perfecto: microespuma sedosa de leche entera que se integra en lugar de flotar. Sin excesos, sin artificios — solo la precisión del grano y la suavidad de la leche en la proporción exacta. Como los mejores momentos en la montaña: simples, honestos y profundamente satisfactorios. El café de quienes saben exactamente lo que quieren.',
    price: 65,
    category: 'hot',
    emoji: '🥛',
    brewType: 'Espresso',
    brewSize: 'Doble shot (6½ oz)',
    tags: ['espresso', 'con leche', 'suave', 'clásico'],
    ingredients: [
      'Doble shot de espresso',
      '5 oz (150 ml) de leche entera',
    ],
    prepSteps: [
      'Insertar la canastilla doble en el portafiltro alineando las pestañas con las muescas. Colocar el embudo e insertar en la cuna de molido.',
      'Girar el dial central hasta iluminar ESPRESSO. Ajustar el dial de molido al tamaño recomendado y presionar START GRIND.',
      'Tampar los granos: presionar el tamper hasta que toque el embudo. Retirar el embudo y fijar el portafiltro en el grupo de extracción alineando los puntos naranjas.',
      'Colocar una taza de 8 oz bajo el portafiltro. Presionar START BREW.',
      'Agregar 5 oz de leche entera fría en la jarra. Colocar en la plataforma con la varita de vapor.',
      'Presionar MILK TYPE hasta iluminar DAIRY. Girar el dial hasta THIN FROTH. Presionar START FROTH.',
      'Verter la leche espumada sobre el espresso y servir.',
    ],
  },
  {
    id: 'cafe-au-lait',
    name: 'Café au Lait',
    description:
      'El equilibrio perfecto entre café de extracción clásica y leche entera espumada: mitad y mitad, sin que ninguno eclipse al otro. Una receta que atravesó fronteras y épocas hasta llegar a estas alturas, donde el café de grano fresco se reúne con la leche cremosa en armonía absoluta. Para los que prefieren el café grande, cálido y con la generosidad de una tarde larga frente a los pinos.',
    price: 50,
    category: 'hot',
    emoji: '🫶',
    brewType: 'Classic',
    brewSize: 'Cup 6 oz',
    tags: ['con leche', 'clásico', 'suave', 'drip'],
    ingredients: [
      '6 oz (180 ml) de café recién preparado (Classic)',
      '5 oz (150 ml) de leche entera',
    ],
    prepSteps: [
      'Insertar la canastilla luxe en el portafiltro alineando las pestañas con las muescas. Colocar el embudo e insertar en la cuna de molido.',
      'Girar el dial central hasta iluminar CLASSIC. Usar el botón SIZE para seleccionar 6 oz. Ajustar el dial de molido al tamaño recomendado y presionar START GRIND.',
      'Retirar el embudo. Fijar el portafiltro en el grupo de extracción alineando los puntos naranjas y girando a la derecha.',
      'Colocar una taza de 12 oz bajo el portafiltro. Presionar START BREW.',
      'Agregar 5 oz de leche entera fría en la jarra. Colocar en la plataforma con la varita de vapor.',
      'Presionar MILK TYPE hasta iluminar DAIRY. Girar el dial hasta THICK FROTH. Presionar START FROTH.',
      'Verter la leche espumada sobre el café y servir.',
    ],
  },
  {
    id: 'cafe-mexicano-especiado',
    name: 'Café Mexicano Especiado',
    description:
      'Donde el café concentrado se encuentra con la audacia de la canela, el chile en polvo y el cayenne — una receta que despierta los sentidos con la misma intensidad que el viento de la sierra al cruzar las cumbres. Coronado con espuma fría de chocolate oscuro que suaviza cada golpe de calor con una nota amarga y sedosa. Complejo, memorable y profundamente mexicano. Para quienes no le temen al sabor.',
    price: 80,
    category: 'hot',
    emoji: '🌶️',
    brewType: 'Rich',
    brewSize: 'Cup 10 oz',
    tags: ['canela', 'chile', 'chocolate', 'intenso', 'especiado', 'drip'],
    ingredients: [
      '10 oz (300 ml) de café recién preparado (Rich)',
      '½ cucharadita de canela molida',
      '¼ cucharadita de chile en polvo',
      '1 pizca de pimienta cayenne',
      '2 oz (60 ml) de crema para batir',
      '1 cucharadita de azúcar glass',
      '2 cucharaditas de cacao en polvo',
    ],
    prepSteps: [
      'Insertar la canastilla luxe en el portafiltro alineando las pestañas con las muescas. Colocar el embudo e insertar en la cuna de molido.',
      'Girar el dial central hasta iluminar RICH. Usar el botón SIZE para seleccionar 10 oz. Ajustar el dial de molido al tamaño recomendado y presionar START GRIND.',
      'Agregar la canela, el chile en polvo y la cayenne en el portafiltro. Golpear suavemente para distribuir sobre los granos.',
      'Retirar el embudo. Fijar el portafiltro en el grupo de extracción alineando los puntos naranjas y girando a la derecha.',
      'Colocar una taza de 14 oz bajo el portafiltro. Presionar START BREW.',
      'Agregar la crema para batir, el azúcar glass y el cacao en polvo en la jarra. Colocar en la plataforma con la varita de vapor.',
      'Presionar MILK TYPE hasta iluminar DAIRY. Girar el dial hasta COLD FOAM. Presionar START FROTH.',
      'Colocar con cuchara la espuma fría de chocolate sobre el café y servir.',
    ],
  },

  // ─── DESSERT ──────────────────────────────────────────────────────────────
  {
    id: 'helado-ambar-arroyo',
    name: 'Ámbar del Arroyo',
    description:
      'Helado artesanal de caramelo dorado, suave como la miel que escurre entre las piedras del arroyo al atardecer. Chispas de chocolate oscuro emergen en cada cucharada como pequeñas piedras del río — intensas, profundas, inesperadamente perfectas. El caramelo, de tonalidades que evocan el sol entre los pinos al ocaso, envuelve el paladar con una dulzura que no necesita justificarse. Un postre que habla de tardes largas y silencios dorados.',
    price: 55,
    category: 'dessert',
    emoji: '🍦',
    brewType: 'Frozen',
    brewSize: 'Copa 300 ml',
    tags: ['helado', 'caramelo', 'chocolate', 'dulce'],
    prepSteps: [
      'Sacar el helado del congelador y dejar reposar 2-3 minutos para suavizar levemente.',
      'Sumergir la cuchara de servir en agua caliente 20-30 segundos para facilitar el porcionado.',
      'Hacer 2-3 bolas generosas y colocarlas en copa o tazón frío.',
      'Añadir una lluvia abundante de chispas de chocolate oscuro sobre las bolas.',
      'Opcional: un hilo de salsa de caramelo extra y una pizca de sal de mar para realzar el sabor.',
      'Servir inmediatamente con cuchara larga.',
    ],
  },
  {
    id: 'helado-niebla-maracuya',
    name: 'Niebla de Maracuyá',
    description:
      'Del trópico a la montaña en un solo bocado. El maracuyá, intenso, vibrante y ligeramente ácido, se encuentra con la serenidad cremosa del yogurt griego en un helado que parece imposible — y sin embargo existe. La acidez frutal corta la riqueza de la crema con la precisión de la niebla del amanecer entre los pinos. Fresco, sorprendente y profundamente satisfactorio. Para quienes buscan algo fuera de lo ordinario en la quietud de la montaña.',
    price: 58,
    category: 'dessert',
    emoji: '🍧',
    brewType: 'Frozen',
    brewSize: 'Copa 300 ml',
    tags: ['helado', 'maracuyá', 'yogurt', 'frutal', 'fresco'],
    prepSteps: [
      'Sacar el helado del congelador y dejar reposar 2-3 minutos.',
      'Sumergir la cuchara de servir en agua caliente para facilitar el porcionado.',
      'Hacer 2-3 bolas y colocarlas en copa o tazón frío.',
      'Añadir una cucharada generosa de yogurt griego natural frío sobre o al lado de las bolas.',
      'Decorar con semillas o un chorro de pulpa de maracuyá fresco para realzar el aroma.',
      'Servir de inmediato para apreciar el contraste entre el frío del helado y la cremosidad del yogurt.',
    ],
  },

  // ─── COLD ────────────────────────────────────────────────────────────────
  {
    id: 'iced-caramel-cold-foam',
    name: 'Café Helado con Espuma de Caramelo Salado',
    description:
      'Café de extracción Over Ice — concentrado y frío desde el primer segundo — coronado con una espuma densa de caramelo y sal marina que equilibra cada sorbo con precisión milimétrica. El contraste entre el amargor del café y la dulzura salada de la espuma es como la montaña y el valle: opuestos que se necesitan mutuamente. La primera probada sorprende; la segunda confirma que no hay nada igual.',
    price: 72,
    category: 'cold',
    emoji: '🧊',
    brewType: 'Over Ice',
    brewSize: 'Cup 10 oz',
    tags: ['frío', 'caramelo', 'sal', 'espuma', 'over ice'],
    ingredients: [
      '10 oz (300 ml) de café Over Ice',
      'Hielo, al gusto',
      '2 oz (60 ml) de crema para batir',
      '1 cucharada de leche entera',
      '2 cucharaditas de jarabe de caramelo',
      '¼ cucharadita de sal kosher',
    ],
    prepSteps: [
      'Insertar la canastilla luxe en el portafiltro alineando las pestañas con las muescas. Colocar el embudo e insertar en la cuna de molido.',
      'Girar el dial central hasta iluminar OVER ICE. Usar el botón SIZE para seleccionar 10 oz. Ajustar el dial de molido al tamaño recomendado y presionar START GRIND.',
      'Retirar el embudo. Fijar el portafiltro en el grupo de extracción alineando los puntos naranjas y girando a la derecha.',
      '⚠️ IMPORTANTE: Llenar un vaso de 16 oz completamente con hielo y colocar bajo el portafiltro. Presionar START BREW.',
      'Agregar la crema para batir, la leche, el jarabe de caramelo y la sal en la jarra. Colocar en la plataforma con la varita de vapor.',
      'Presionar MILK TYPE hasta iluminar DAIRY. Girar el dial hasta COLD FOAM. Presionar START FROTH.',
      'Colocar con cuchara la espuma fría de caramelo salado sobre el café y servir.',
    ],
  },
  {
    id: 'vietnamese-iced-coffee',
    name: 'Café Vietnamita',
    description:
      'Un viaje al sureste asiático desde las alturas de la sierra: café Over Ice potente y con carácter, agitado vigorosamente con leche condensada azucarada hasta crear una textura sedosa y caramelizada sin paralelo. La leche condensada no solo endulza — transforma. El resultado es un café que es también postre, también historia, también una tarde perfecta que no se olvida.',
    price: 68,
    category: 'cold',
    emoji: '🌿',
    brewType: 'Over Ice',
    brewSize: 'Cup 10 oz',
    tags: ['frío', 'leche condensada', 'dulce', 'agitado', 'over ice'],
    ingredients: [
      '10 oz (300 ml) de café Over Ice',
      'Hielo, al gusto',
      '3 cucharadas de leche condensada azucarada',
    ],
    prepSteps: [
      'Insertar la canastilla luxe en el portafiltro alineando las pestañas con las muescas. Colocar el embudo e insertar en la cuna de molido.',
      'Girar el dial central hasta iluminar OVER ICE. Usar el botón SIZE para seleccionar 10 oz. Ajustar el dial de molido al tamaño recomendado y presionar START GRIND.',
      'Retirar el embudo. Fijar el portafiltro en el grupo de extracción alineando los puntos naranjas y girando a la derecha.',
      'Llenar un coctelero con hielo y agregar 3 cucharadas de leche condensada azucarada. Colocar bajo el portafiltro y presionar START BREW.',
      'Una vez que el café termine de extraerse, colocar la tapa al coctelero y agitar vigorosamente por 10 segundos.',
      'Transferir el café agitado a un vaso de 16 oz y servir.',
    ],
  },
  {
    id: 'cold-brew-caramel-almond',
    name: 'Cold Brew de Caramelo y Almendra',
    description:
      'Cold brew extraído a baja temperatura para capturar la dulzura natural del grano, luego realzado con jarabe de caramelo y la ligereza vegetal de la leche de almendra. Suave, limpio y profundamente refrescante — como un arroyo de montaña entre piedras al amanecer. Sin acidez forzada, sin amargor innecesario. Solo café en su expresión más serena.',
    price: 65,
    category: 'cold',
    emoji: '🌰',
    brewType: 'Cold Brew',
    brewSize: 'Cup 10 oz',
    tags: ['frío', 'cold brew', 'caramelo', 'almendra', 'vegano'],
    ingredients: [
      '10 oz (300 ml) de cold brew',
      'Hielo, al gusto',
      '3 cucharadas de leche de almendra',
      '1 cucharada de jarabe de caramelo',
    ],
    prepSteps: [
      'Insertar la canastilla luxe en el portafiltro alineando las pestañas con las muescas. Colocar el embudo e insertar en la cuna de molido.',
      'Girar el dial central hasta iluminar COLD BREW. Usar el botón SIZE para seleccionar 10 oz. Ajustar el dial de molido al tamaño recomendado y presionar START GRIND.',
      'Retirar el embudo. Fijar el portafiltro en el grupo de extracción alineando los puntos naranjas y girando a la derecha.',
      '⚠️ IMPORTANTE: Llenar un vaso de 12 oz con hielo, agregar 1 cucharada de jarabe de caramelo y colocar bajo el portafiltro. Presionar START BREW (la extracción tarda 5–10 minutos).',
      'Una vez que el café termine, agregar 3 cucharadas de leche de almendra, revolver y servir.',
    ],
  },
  {
    id: 'iced-hazelnut-latte',
    name: 'Latte Helado de Avellana',
    description:
      'Espresso cold-pressed — extraído frío para preservar las notas más suaves del grano — encontrando su match perfecto en jarabe de avellana y leche entera fría. Aromático, cremoso y completamente adictivo: como encontrar una cabaña iluminada entre los pinos cuando la tarde ya oscurece. Refrescante pero con carácter, frío pero con toda la profundidad del espresso.',
    price: 70,
    category: 'cold',
    emoji: '🌙',
    brewType: 'Cold-Pressed',
    brewSize: 'Doble shot (9½ oz)',
    tags: ['frío', 'espresso', 'avellana', 'con leche', 'cold-pressed'],
    ingredients: [
      'Doble shot de espresso (cold-pressed)',
      '1 cucharada de jarabe de avellana',
      '1 taza (8 oz / 240 ml) de leche entera',
      'Hielo, al gusto',
    ],
    prepSteps: [
      'Insertar la canastilla doble en el portafiltro alineando las pestañas con las muescas. Colocar el embudo e insertar en la cuna de molido.',
      'Girar el dial central hasta iluminar COLD-PRESSED. Ajustar el dial de molido al tamaño recomendado y presionar START GRIND.',
      'Tampar los granos: presionar el tamper hasta que toque el embudo. Retirar el embudo y fijar el portafiltro en el grupo de extracción alineando los puntos naranjas.',
      'Agregar 1 cucharada de jarabe de avellana en un vaso de 12 oz lleno con hielo y colocar bajo el portafiltro. Presionar START BREW.',
      'Una vez extraído el espresso, agregar 1 taza (8 oz) de leche entera fría, revolver y servir.',
    ],
  },
];
